name: Terraform CI/CD

on:
  push:
    branches:
      - main  # Alvo da branch para disparar a pipeline
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Aplicar Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configuração do AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'  # Ajuste para a região que está utilizando

      - name: Instalar o Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y wget unzip
          wget https://releases.hashicorp.com/terraform/1.10.5/terraform_1.10.5_linux_arm64.zip
          unzip -o terraform_1.10.5_linux_arm64.zip
          cd terraform_1.10.5_linux_arm64
          # Verificar e remover qualquer diretório/arquivo chamado terraform em /usr/local/bin
          if [ -e /usr/local/bin/terraform ]; then
            sudo rm -rf /usr/local/bin/terraform  # Remove o diretório ou arquivo existente
          fi
          sudo mv terraform /usr/local/bin/

      # - name: Inicializar o Terraform
      #   run: terraform init

      # - name: Validar configuração do Terraform
      #   run: terraform validate

      # - name: Aplicar o Terraform
      #   run: terraform apply -auto-approve -var-file=terraform/env/${{ github.event_name }}.tfvars

      # - name: Exibir o output do Terraform
      #   run: terraform output
