name: Terraform CI/CD

on:
  push:
    branches:
      - main  # Alvo da branch para disparar a pipeline
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Aplicar Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configuração do AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'  # Ajuste para a região que está utilizando

      - name: Instalar o Terraform
        run: |
          ls -la /usr/local/bin/terraform
          # sudo apt-get update && sudo apt-get install -y wget unzip
          # wget https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
          # unzip -o terraform_1.5.0_linux_amd64.zip
          # Remove qualquer diretório ou arquivo 'terraform' existente
          # sudo rm -f /usr/local/bin/terraform
          # sudo mv terraform /usr/local/bin/

      # - name: Inicializar o Terraform
      #   run: terraform init

      # - name: Validar configuração do Terraform
      #   run: terraform validate

      # - name: Aplicar o Terraform
      #   run: terraform apply -auto-approve -var-file=terraform/env/${{ github.event_name }}.tfvars

      # - name: Exibir o output do Terraform
      #   run: terraform output
